### ISSUE TITLE
actas - são muito grandes - lista devia estar no topo?

### ISSUE THREAD

**Issue by dncpax** [ulmi/ulmi.github.io#12]
como as actas são muito grandes esta página não funciona bem...
mostrar só excerpto ou passar a lista para cima?

**Comment by ulmi** [comment]
Já tá resolvido...esqueceste de colocar o  que é para cortar.

**Comment by dncpax** [comment]
hehe, não foi bem esquecer... não tinha ideia que o markdown tinha isso...
